---
title: "JEDERGEGENJEDEN 100perGEOMORPH"
author: "fabian gruber"
date: "April 24, 2017"
output: html_document
---

Die Erebgenisse der neuesten Berechnungen (OSTERN 2017)


```{r,include=FALSE}
library(RCurl)
library(rgrass7)
library(repmis)
require(xtable)
myfunctions <- getURL("https://raw.githubusercontent.com/fernstgruber/Rstuff/master/fabiansandrossitersfunctions.R", ssl.verifypeer = FALSE)
eval(parse(text = myfunctions))
source_data("https://github.com/fernstgruber/p2/blob/master/data2017/geotopodata_twohundredpergeomorph_2017.RData?raw=true")
classes <- levels(modeldata$geomorphologie_beschreibung)
rm(modeldata)
```

```{r}
base="/media/fabs/Volume/01_PAPERZEUG/newstuff_p2/"
classes <- classes[-c(2,18)]
p=paramsetnames[1]
for(p in paramsetnames){
  mydir=paste(base,"svm_2017_1against1_5foldgeomorph_",p,"_100pg_t10",sep="")
  cl=classes[1]
  for(cl in classes){
    newclasses <- classes[!(classes %in% cl)]
    newclass=newclasses[1]
    for(newclass in newclasses){
      modelclasses <- c(cl,newclass)
      mynewdir = paste(mydir,"/",cl,"_vs_",newclass,sep="")
      print(paste(cl,"_vs_",newclass,sep=""))
      try(evaluateforwardCV_anyerror(mypath=mynewdir,kk = 1:5,endround = 10,error = "cverror",geheim="geheimerprederror",yrange=c(0,1)))
}
}
}
```