---
title: "importance of terrain parameters based on random forests"
author: "fabian gruber"
date: "August 4, 2017"
output: html_document
---

```{r setup, include=FALSE}
require(randomForest)
require(RCurl)
require(repmis)
myfunctions <- getURL("https://raw.githubusercontent.com/fernstgruber/Rstuff/master/fabiansandrossitersfunctions.R", ssl.verifypeer = FALSE)
eval(parse(text = myfunctions))
source_data("https://github.com/fernstgruber/p2/blob/master/data2017/geotopodata_twohundredpergeomorph_2017.RData?raw=true")
rm(modeldata)
source_data("https://github.com/fernstgruber/p2/blob/master/data2017/modeldata_onehundredpergeomorph.RData?raw=true")
origmodeldata <- modeldata
origmodeldata$Festgestein <- ifelse(is.na(origmodeldata$Festgestein),yes = 0,no = 1)
origmodeldata$Festgestein <- as.factor(origmodeldata$Festgestein)
dependent=geospalten[1]
preds <- allpreds
fullmodelcols <- c(dependent,preds)
paramsetnames
paramsets[[1]] <- paramsets[[1]][-c(156,162:163,196)]
paramsets[[5]] <- paramsets[[5]][-c(80:82,84:93,95:102)]
paramsets[[2]] <- paramsets[[2]][-c(132:133)]
paramsets[[3]] <- paramsets[[3]][-c(2,15)]
paramsets[[4]] <- paramsets[[4]][-c(5,8,10,13,15,18,20,23,25,28,30,33,35,38,40,43,45,48,50,53,55,58,60,63,65,68,70,72,73,76,78,81,83,86,88,91,93,96,98,101,103,106,108,
                                    111,113,116,118,121,123,126,128,131,133,136,138,141,143,146,148,151,153,156,158,161,163,164,165,168,170,173,175,178,180,183,185)]
paramsets[[4]] <- paramsets[[4]][-c(44)]
#########################################################################################
psets <- c(1:7)
classes <-  levels(origmodeldata[[dependent]])
paramsetnames = paramsetnames[psets]
paramsets = paramsets[psets]

p=paramsets[1]
```

```{r}
n=1
for (p in paramsets){
predset_name <- paramsetnames[n]
print(predset_name)
preds <- unlist(p)
mymodeldata <- na.omit(origmodeldata[c(dependent,preds)])
f <- paste(dependent,"~.")
fit <- do.call("randomForest",list(as.formula(f),mymodeldata))
importance <- as.data.frame(fit$importance)
importance$parameters <- row.names(importance)
importance <- importance[order(importance$MeanDecreaseGini,decreasing = T),]
print(importance[1:10,])
fit$err.rate
print(paste("OOB error rate: ", fit$err.rate[nrow(fit$err.rate),1]))
n=n+1
}
```


