---
title: "Predicting parentmaterial - foward feature selection"
author: "fabian gruber"
date: "October 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
require(e1071)
require(RCurl)
require(repmis)
require(randomForest)
myfunctions <- getURL("https://raw.githubusercontent.com/fernstgruber/Rstuff/master/fabiansandrossitersfunctions.R", ssl.verifypeer = FALSE)
eval(parse(text = myfunctions))
load("/home/fabs/Data/paper2data/profiledata.RData")
allpreds <- c(localterrain,regionalterrain,roughness,heights)
paramsets <- list(localterrain,regionalterrain,roughness,heights,allpreds)
paramsetnames <- c("localterrain","regionalterrain","roughness","heights","allpreds")
dependent="SGU_kartiert"
allpreds <- c(localterrain,regionalterrain,roughness,heights)
allpreds <- c(allpreds[allpreds %in% names(profiledata)])
nadata <- na.omit(profiledata)
problempunkte <- profiledata[!(profiledata$ID %in% nadata$ID),]
profiledata <- profiledata[profiledata$ID != "12884", ]
badones <-vector()
for(pp in allpreds){
  if(nrow(profiledata[is.na(profiledata[[pp]]),]) > 0) {
    badones <-c(badones,pp)
  }
}
allpreds=allpreds[!(allpreds %in% badones)]
paramsets[[5]] <- allpreds
localterrain <- localterrain[localterrain %in% allpreds]
paramsets[[1]] <- localterrain
origmodeldata <- profiledata[names(profiledata) %in% c(dependent,"SGU_gk",allpreds)]
#########################################################################################
```
##Overview of point distribution
# surveyed:
```{r}
table(origmodeldata$SGU_kartiert)
```

# geological map:
```{r}
table(origmodeldata$SGU_gk)
```


##Allpreds
###SVM
```{r}
evaluateforwardCV_anyerror(mypath = "/home/fabs/PROJECTP2/temporlarge/svm_fw_5fold_5p_SGU_kartiert_allpreds/",kk = 1:5,endround = 5,geheim = "geheimerprederror",error = "cverror")
predict_radial_full(modeldata=origmodeldata,dependent = "SGU_kartiert",predictors = c("SGU_gk","LS_Factor_50m","maxic_DTM_50m_avg_ws9_50m"))
```
localterrain
```{r}
evaluateforwardCV_anyerror(mypath = "/home/fabs/PROJECTP2/temporlarge/svm_fw_5fold_5p_SGU_kartiert_localterrain/",kk = 1:5,endround = 5,geheim = "geheimerprederror",error = "cverror")
predict_radial_full(modeldata=origmodeldata,dependent = "SGU_kartiert",predictors = c("SGU_gk","LS_Factor_50m","maxic_DTM_50m_avg_ws9_50m"))

```

regional terrain
```{r}
evaluateforwardCV_anyerror(mypath = "/home/fabs/PROJECTP2/temporlarge/svm_fw_5fold_5p_SGU_kartiert_regionalterrain/",kk = 1:5,endround = 5,geheim = "geheimerprederror",error = "cverror")
predict_radial_full(modeldata=origmodeldata,dependent = "SGU_kartiert",predictors = c("SGU_gk","LS_Factor_50m","maxic_DTM_50m_avg_ws9_50m"))

```


roughness
```{r}
evaluateforwardCV_anyerror(mypath = "/home/fabs/PROJECTP2/temporlarge/svm_fw_5fold_5p_SGU_kartiert_roughness/",kk = 1:5,endround = 5,geheim = "geheimerprederror",error = "cverror")
predict_radial_full(modeldata=origmodeldata,dependent = "SGU_kartiert",predictors = c("SGU_gk","TRI_hr_ws31","geom_hr_L50m_fl10_rplipmps_UE_hr_40cells_hr"))
predict_radial_full(modeldata=origmodeldata,dependent = "SGU_kartiert",predictors = c("SGU_gk","TRI_hr_ws31","terraintexture_hr_ws41_t1"))
```



