---
title: "profilepoint analysis alluvial deposits"
author: "fabian gruber"
date: "October 24, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r,echo=F,include=F}
require(e1071)
require(RCurl)
require(repmis)
require(randomForest)
proj2path="/media/fabs/Volume/01_PAPERZEUG/PROJECTP2/"
myfunctions <- getURL("https://raw.githubusercontent.com/fernstgruber/Rstuff/master/fabiansandrossitersfunctions.R", ssl.verifypeer = FALSE)
eval(parse(text = myfunctions))
legend <- read.table(paste(proj2path,"data2017/SGU_legend_new.txt",sep=""),sep="\t",header=T)
load(paste(proj2path,"data2017/modeldata_sGUkartiert.RData",sep=""))
modeldataoktober$SGU_gk <- factor(modeldataoktober$SGU_gk,levels=levels(legend$SGU))
modeldataoktober$SGU_kartiert <- factor(modeldataoktober$SGU_kartiert,levels=levels(legend$SGU))
profile <- sqliteGRASS_delilah(location="EPPAN_vhr",mapset = "paper3data_predictparentmaterial",vector = "paper3data_predictparentmaterial_Profilpunktemitboden_UTM")
sampledata <- sqliteGRASS_delilah(location="EPPAN_vhr",mapset = "paper3data_predictparentmaterial",vector = "paper3data_predictparentmaterial_100m_grid_SGU")
sampledata$geolegen_1 <- as.factor(sampledata$geolegen_1)
local <- unlist(paramsets[1])
local <- local[local %in% names(modeldataoktober)]
paramsets[1] <- list(local)
load(file="/media/fabs/Volume/01_PAPERZEUG/paper2data/sampledata_100mgrid.RData")

```



```{r,results = 'asis',echo=F}
cl1= "AD"
dependent="correct"
relevantmodeldata <- modeldataoktober[(modeldataoktober$SGU_kartiert == as.character(cl1)),]
relevantmodeldata$correct <- ifelse(relevantmodeldata$SGU_kartiert == relevantmodeldata$SGU_gk,1,0)
relevantmodeldata$correct<-as.factor(relevantmodeldata$correct)
summary(relevantmodeldata$correct)
allimp <- increaseacc(modeldata = relevantmodeldata,pset = 5,dependent = dependent)
roughimp <- increaseacc(modeldata = relevantmodeldata,pset = 3,dependent = dependent)
localimp <- increaseacc(modeldata = relevantmodeldata,pset = 1,dependent = dependent)
  par(mfcol=c(1,3))
boxplot(data=relevantmodeldata[c(as.character(rownames(allimp)[1]),dependent)],as.formula(paste(as.character(rownames(allimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(allimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(roughimp)[1]),dependent)],as.formula(paste(as.character(rownames(roughimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(roughimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(localimp)[1]),dependent)],as.formula(paste(as.character(rownames(localimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(localimp)[1]))

```

How are these points morphometrically different from others
For instance different to till in general

```{r,results = 'asis',echo=F}
cl1="AD"
cl2="TG"
dependent="SGU_kartiert"
relevantmodeldata <- modeldataoktober[modeldataoktober$SGU_kartiert %in% c(cl1,cl2),]
relevantmodeldata$SGU_kartiert <- droplevels(relevantmodeldata$SGU_kartiert)
evaluateforwardCV_anyerror(mypath = paste(proj2path,"data2017/temprdata/RanFor_1on1_5foldprofilesitesallpredsp3/",cl1,"_vs_",cl2,sep=""),kk = 1:5,endround = 3,error = "cverror",geheim="geheimerprederror",yrange=c(0,0.5))
allimp <- increaseacc(modeldata = relevantmodeldata,pset = 5,dependent = dependent)
kable(allimp)
roughimp <- increaseacc(modeldata = relevantmodeldata,pset = 3,dependent = dependent)
kable(roughimp)
localimp <- increaseacc(modeldata = relevantmodeldata,pset = 1,dependent = dependent)
kable(localimp)
par(mfcol=c(1,3))
boxplot(data=relevantmodeldata[c(as.character(rownames(allimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(allimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(allimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(roughimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(roughimp)[1]),"~ ", dependent,sep=" ")),outline=F,main=as.character(rownames(roughimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(localimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(localimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(localimp)[1]))
```
  
  How does this compare to the differences between the units on the geological map?  
  
```{r,results = 'asis',echo=F}
cl1="AD"
cl2="TG"
dependent="geolegen_1" 
relevantmodeldata <- sampledata[sampledata$geolegen_1 %in% c(cl1,cl2),]
relevantmodeldata$geolegen_1<- as.factor(relevantmodeldata$geolegen_1)
#evaluateforwardCV_anyerror(mypath = paste("/home/fabs/PROJECTP2/data2017/temprdata/RanFor_1on1_5foldprofilesitesallpredsp3/",cl1,"_vs_",cl2,sep=""),kk = 1:5,endround = 3,error = "cverror",geheim="geheimerprederror",yrange=c(0,0.5))
allimp <- increaseacc(modeldata = relevantmodeldata,pset = 5,dependent = dependent)
kable(allimp)
roughimp <- increaseacc(modeldata = relevantmodeldata,pset = 3,dependent = dependent)
kable(roughimp)
localimp <- increaseacc(modeldata = relevantmodeldata,pset = 1,dependent = dependent)
kable(localimp)
  par(mfcol=c(1,3))
boxplot(data=relevantmodeldata[c(as.character(rownames(allimp)[1]),dependent)],as.formula(paste(as.character(rownames(allimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(allimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(roughimp)[1]),dependent)],as.formula(paste(as.character(rownames(roughimp)[1]),"~ ", dependent,sep=" ")),outline=F,main=as.character(rownames(roughimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(localimp)[1]),dependent)],as.formula(paste(as.character(rownames(localimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(localimp)[1]))
```

How about Debris cones

```{r,results = 'asis',echo=F}
cl1="AD"
cl2="DC"
dependent="SGU_kartiert"
relevantmodeldata <- modeldataoktober[modeldataoktober$SGU_kartiert %in% c(cl1,cl2),]
relevantmodeldata$SGU_kartiert <- droplevels(relevantmodeldata$SGU_kartiert)
evaluateforwardCV_anyerror(mypath = paste(proj2path,"data2017/temprdata/RanFor_1on1_5foldprofilesitesallpredsp3/",cl1,"_vs_",cl2,sep=""),kk = 1:5,endround = 3,error = "cverror",geheim="geheimerprederror",yrange=c(0,0.5))
allimp <- increaseacc(modeldata = relevantmodeldata,pset = 5,dependent = dependent)
kable(allimp)
roughimp <- increaseacc(modeldata = relevantmodeldata,pset = 3,dependent = dependent)
kable(roughimp)
localimp <- increaseacc(modeldata = relevantmodeldata,pset = 1,dependent = dependent)
kable(localimp)
par(mfcol=c(1,3))
boxplot(data=relevantmodeldata[c(as.character(rownames(allimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(allimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(allimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(roughimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(roughimp)[1]),"~ ", dependent,sep=" ")),outline=F,main=as.character(rownames(roughimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(localimp)[1]),"SGU_kartiert")],as.formula(paste(as.character(rownames(localimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(localimp)[1]))
```
  
  How does this compare to the differences between the units on the geological map?  
  
```{r,results = 'asis',echo=F}
cl1="AD"
cl2="DC"
dependent="geolegen_1" 
relevantmodeldata <- sampledata[sampledata$geolegen_1 %in% c(cl1,cl2),]
relevantmodeldata$geolegen_1<- as.factor(relevantmodeldata$geolegen_1)
#evaluateforwardCV_anyerror(mypath = paste("/home/fabs/PROJECTP2/data2017/temprdata/RanFor_1on1_5foldprofilesitesallpredsp3/",cl1,"_vs_",cl2,sep=""),kk = 1:5,endround = 3,error = "cverror",geheim="geheimerprederror",yrange=c(0,0.5))
allimp <- increaseacc(modeldata = relevantmodeldata,pset = 5,dependent = dependent)
kable(allimp)
roughimp <- increaseacc(modeldata = relevantmodeldata,pset = 3,dependent = dependent)
kable(roughimp)
localimp <- increaseacc(modeldata = relevantmodeldata,pset = 1,dependent = dependent)
kable(localimp)
  par(mfcol=c(1,3))
boxplot(data=relevantmodeldata[c(as.character(rownames(allimp)[1]),dependent)],as.formula(paste(as.character(rownames(allimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(allimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(roughimp)[1]),dependent)],as.formula(paste(as.character(rownames(roughimp)[1]),"~ ", dependent,sep=" ")),outline=F,main=as.character(rownames(roughimp)[1]))
boxplot(data=relevantmodeldata[c(as.character(rownames(localimp)[1]),dependent)],as.formula(paste(as.character(rownames(localimp)[1]),"~ ", dependent,sep=" ")),outline=T,main=as.character(rownames(localimp)[1]))
```
