require(rgrass7)
library(RCurl)
library(repmis)
require(xtable)
require(rgdal)
geolegendeng <- read.table(text=getURL("https://raw.githubusercontent.com/fernstgruber/p2/master/data2017/geolegendeng.txt"),sep="\t",header=T)
myfunctions <- getURL("https://raw.githubusercontent.com/fernstgruber/Rstuff/master/fabiansandrossitersfunctions.R", ssl.verifypeer = FALSE)
eval(parse(text = myfunctions))
south <- readOGR(dsn="/home/fabs/Data/paper2data/100m_grid_SGU_south.shp",layer="100m_grid_SGU_south")
north <- readOGR(dsn="/home/fabs/Data/paper2data/100m_grid_SGU_north.shp",layer="100m_grid_SGU_north")
names(south)
summary(south$geolegen_1)
summary(north$geolegen_1)
geolegendeng
