---
title: "boxplots for SGUs"
author: "fabian gruber"
date: "September 15, 2017"
output: html_document
---

```{r, include=FALSE}
varlist <- c("ChannelNetworkBaseLevel","Channel_Network_Base_Level","Convexity","Longitudinal_Curvature",
             "Maximum_Height_hr","Normalized_Height","TPI_i0m_o500m","TRI_hr_ws26","Texture",
             "VerticalDistancetoChannelNetwork","aspect_ws15_hr","bodenbedeckung","crosc_DTM_50m_avg_ws3",
             "crosc_DTM_50m_avg_ws7","geom_dtm_10m_hyd_fl5_L30","geom_hr_L3_fl1_r.li.simpson_UE_hr_40cells",
             "hoehenstufen","longc_DTM_50m_avg_ws7","profc_DTM_50m_avg_ws7","slope_DTM_50m_avg_ws3",
             "slope_DTM_50m_avg_ws7","slope_ws15","slope_ws15_hr")
numericlist <-  c("ChannelNetworkBaseLevel","Channel_Network_Base_Level","Convexity","Longitudinal_Curvature",
                  "Maximum_Height_hr","Normalized_Height","TPI_i0m_o500m","TRI_hr_ws26","Texture",
                  "VerticalDistancetoChannelNetwork","aspect_ws15_hr","crosc_DTM_50m_avg_ws3",
                  "crosc_DTM_50m_avg_ws7","geom_dtm_10m_hyd_fl5_L30","geom_hr_L3_fl1_r.li.simpson_UE_hr_40cells",
                  "longc_DTM_50m_avg_ws7","profc_DTM_50m_avg_ws7","slope_DTM_50m_avg_ws3",
                  "slope_DTM_50m_avg_ws7","slope_ws15","slope_ws15_hr")
```



```{r,echo=FALSE}
load(file="/media/fabs/Volume/01_PAPERZEUG/PROJECTP2/temporlarge/SGU_df_bis8.RData")
num=numericlist[1]
for (num in numericlist[1]){
  print(paste(num))
  boxplot(data=sgu_df,as.formula(paste(num,"~","Abbrev.")),las=2,main=as.character(num))
}
rm(sgu_df)
```