---
title: "soil distribution from both viewpoints"
author: "fabian gruber"
date: "October 3, 2017"
output: html_document
---
```{r,include=F}
library(knitr)
load("/home/fabs/PROJECTP2/data2017/boden_SGU.RData")
boden_SGU <- boden_SGU[boden_SGU$KLASSE != "",]
boden_SGU <- boden_SGU[boden_SGU$TYP != "",]
boden_SGU <- boden_SGU[boden_SGU$SUBTYP != "",]
boden_SGU[boden_SGU$ID=="9_U","SUBTYP"] <- "Typischer Ranker"
boden_SGU[boden_SGU$ID=="58_T","SUBTYP"] <- "Typischer Ranker"
boden_SGU[boden_SGU$ID=="33_U","SUBTYP"] <- "Typischer Ranker"
boden_SGU[boden_SGU$ID=="22_U","SUBTYP"] <- "Typischer Ranker"
boden_SGU[boden_SGU$SUBTYP=="Ranker","SUBTYP"] <- "Typischer Ranker"
boden_SGU <- droplevels(boden_SGU)
summary(boden_SGU$KLASSE)
Klassen <- levels(boden_SGU$KLASSE)
Klassen
Typen <- levels(boden_SGU$TYP)
Typen
Subtypen <- levels(boden_SGU$SUBTYP)
Subtypen
summary(boden_SGU$SUBTYP)
bodenpunkte <- unique(boden_SGU$ID)
levels(boden_SGU$KLASSE)
boden_SGU$KLASSE <- factor(boden_SGU$KLASSE,levels=levels(boden_SGU$KLASSE)[c(7,6,1,3,2,5,8,4)])
summary(boden_SGU$KLASSE)
levels(boden_SGU$TYP)
boden_SGU$TYP <- factor(boden_SGU$TYP,levels=levels(boden_SGU$TYP)[c(4,3,12,7,10,11,1,9,15,6,2,16,8,13,14,5)])
summary(boden_SGU$TYP)
levels(boden_SGU$SUBTYP)
boden_SGU$SUBTYP <- factor(boden_SGU$SUBTYP,levels=levels(boden_SGU$SUBTYP)[c(3,8,7,25,18,20,14,19,16,22,17,29,2,28,24,6,1,21,26,13,11,27,15,4,9,5,10,23,12)])
summary(boden_SGU$SUBTYP)
```



```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$KLASSE,boden_SGU$SGU_gk)),caption="Distribution of the soil typ classes on the SGUs of the geological map")
```

```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$KLASSE,boden_SGU$SGU_kartiert)),caption="Distribution of the soil typ classes on the SGUs as interpreted by the surveyor")
```

```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$TYP,boden_SGU$SGU_gk)),caption="Distribution of the soil types on the SGUs of the geological map")
```

```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$TYP,boden_SGU$SGU_kartiert)),caption="Distribution of the soil types on the SGUs as interpreted by the surveyor")
```

```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$SUBTYP,boden_SGU$SGU_gk)),caption="Distribution of the soil subtypes on the SGUs of the geological map")
```

```{r,echo=FALSE}
kable(as.data.frame.matrix(table(boden_SGU$SUBTYP,boden_SGU$SGU_kartiert)),caption="Distribution of the soil subtypes on the SGUs as interpreted by the surveyor")
```

```{r,echo=FALSE}
i = levels(boden_SGU$SGU_gk)[1]
for ( i in levels(boden_SGU$SGU_gk)){
  kart <- boden_SGU[boden_SGU$SGU_kartiert == as.character(i),]
kart <- droplevels(kart)
  geo <- boden_SGU[boden_SGU$SGU_gk == as.character(i),]
  geo <- droplevels(geo)
  print("***********************************************************************************")
    print("**************************SOIL CLASSES**********************************************")
print(paste("Distribution of the soil subtypes on",i, "as identified on geological map"))
print(table(geo$KLASSE))
print(paste("Distribution of the soil subtypes on",i, "as interpreted by the surveyor"))
print(table(kart$KLASSE))
 print("**************************SOIL TYPES************************************************")
 print(paste("Distribution of the soil types on",i, "as identified on geological map"))
print(table(geo$TYP))
print(paste("Distribution of the soil types on",i, "as interpreted by the surveyor"))
print(table(kart$TYP))
print("**************************SOIL SUBTYPES*********************************************")
print(paste("Distribution of the soil subtypes on",i, "as identified on geological map"))
print(table(geo$SUBTYP))
print(paste("Distribution of the soil subtypes on",i, "as interpreted by the surveyor"))
print(table(kart$SUBTYP))
}
```

